name: greengrocer
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.4.0
  intl: ^0.18.0
  fluttertoast: ^8.0.8
  add_to_cart_animation: ^0.0.7
  shimmer: ^2.0.0
  get: ^4.6.5
  dio: ^5.1.1
  json_annotation: ^4.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_secure_storage: ^8.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/app_images/

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/app_images/app_icon.png"